### ISSUE TITLE
Book does not build

### ISSUE THREAD

**Issue by keszocze** [schoeberl/chisel-book#62]
I tried building the book from the [latest release](https://github.com/schoeberl/chisel-book/archive/refs/tags/v5.0.zip) but it is the same when cloning the repository. It fails with the following error message
```bash
$ make book
[....]
! Package Listings Error: File `code/hello(.txt)' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: txt)
```
The error comes from [this line](https://github.com/schoeberl/chisel-book/blob/63986db5aafdfaa07d58e7a1ff680cf9a44db298/chisel-book.tex#L623):
```latex
\longlist{code/hello.txt}{A hardware Hello World in Chisel}{lst:chisel:hello}
```
There is no `code` folder and I can't find any fitting text files at all:
```
$ find . -name '*.txt'
./data.txt
```

**Comment by schoeberl** [comment]
Why not do a plain
```
make
```
That should include the creation of the .txt files from the Chisel source.

**Comment by keszocze** [comment]
Because that failed with annoying error messages regarding the Chisel code that I did not want to debug. I expected that `make book` would be enough to build the book but I have to admit that I was a bit lazy. The solution is to call `make gencode fig book`.


Running `make` from the release I get the error
```
[error] java.lang.RuntimeException: expected `chisel-book-5-0/scalaVersion` to be "2.13.10" or later,
[error] but found "2.13.8"; upgrade scalaVersion to fix the build.
```
due to a call to `sbt test`. This confuses me as I have the following versions installed that clearly are above the required version:
```
$ scala --version
Scala code runner version 3.4.2 -- Copyright 2002-2024, LAMP/EPFL

$ scalac --version
Scala compiler version 3.4.2 -- Copyright 2002-2024, LAMP/EPFL

$ scala 
scala> util.Properties.versionMsg
val res1: String = Scala library version 2.13.12 -- Copyright 2002-2023, LAMP/EPFL and Lightbend, Inc.
```

Changing the lines in `build.sbt` as follows
```SBT
// was scalaVersion := "2.13.8"
scalaVersion := "2.13.10"
```
or removing it entirely (as you do on the `main` branch) does not help. It simply yields the problem [described here](https://github.com/sbt/sbt/issues/7131). Switching back to the century old Java 8 solved the problem (the claim that updating `sbt` will allow you to use Java 21, at least on my system, was not true).

 Still, calling `make all` will not generate the slides and the book in case any of the tests fail (I don't have verilator or z3 installed right now).

**Comment by schoeberl** [comment]
I think I still should fix this. This is probably an issue with the Scala version related to Java: https://docs.scala-lang.org/overviews/jdk-compatibility/overview.html
I have yet to explore different Java versions and Chisel/Scala. Where is the claim on sbt? In the book?

I will briefly switch to Chisel 6 and the latest supported Scala version. Can you try again?

Thanks for helping me debug this issue.

**Comment by keszocze** [comment]
Just another thing: The slides don't build on my system:
```
! LaTeX Error: Unknown option 'pdflatex' for package xcolor.
```

I will investigate this after the checking with chisel 6.

**Comment by keszocze** [comment]
> I have yet to explore different Java versions and Chisel/Scala. Where is the claim on sbt? In the book?

It was from [the issue](https://github.com/sbt/sbt/issues/7131) I was referring to in my previous post.

**Comment by keszocze** [comment]
With 
```
scalaVersion := "2.13.14"
val chiselVersion = "5.3.0"
addCompilerPlugin("org.chipsalliance" % "chisel-plugin" % chiselVersion cross CrossVersion.full)
libraryDependencies += "org.chipsalliance" %% "chisel" % chiselVersion
libraryDependencies += "edu.berkeley.cs" %% "chiseltest" % "5.0.2"
```
it works for Java 8 and Java 21 except for one failing test case:
```
[info] - should pass *** FAILED ***
[info]   scala.NotImplementedError: TODO: convert LoadMemoryAnnotation(ComponentName(mem,ModuleName(InitMemory,CircuitName(InitMemory))),hello.hex,Hex,Some(mem))
[info]   at chiseltest.simulator.ChiselBridge$.convert(ChiselBridge.scala:151)
[info]   at chiseltest.simulator.ChiselBridge$.$anonfun$annosToState$2(ChiselBridge.scala:93)
[info]   at scala.collection.immutable.List.flatMap(List.scala:294)
[info]   at scala.collection.immutable.List.flatMap(List.scala:79)
[info]   at chiseltest.simulator.ChiselBridge$.annosToState(ChiselBridge.scala:93)
[info]   at chiseltest.simulator.ChiselBridge$.elaborate(ChiselBridge.scala:73)
[info]   at chiseltest.simulator.Compiler$.elaborate(Compiler.scala:19)
[info]   at chiseltest.internal.BackendExecutive$.start(BackendExecutive.scala:23)
[info]   at chiseltest.defaults.package$.createDefaultTester(defaults.scala:25)
[info]   at chiseltest.ChiselScalatestTester$TestBuilder.apply(ChiselScalatestTester.scala:32)
```

When switching to 
```
scalaVersion := "2.13.14"
val chiselVersion = "6.5.0"
addCompilerPlugin("org.chipsalliance" % "chisel-plugin" % chiselVersion cross CrossVersion.full)
libraryDependencies += "org.chipsalliance" %% "chisel" % chiselVersion
libraryDependencies += "edu.berkeley.cs" %% "chiseltest" % "6.0.0"
```
I get another failing test for bot Java versions:
```
[info] - should pass *** FAILED ***
[info]   In step 1: io_rdData=0 (0x0) did not equal expected=72 (0x48) at (MemoryTest.scala:129) (MemoryTest.scala:129)
```
which seems to be an actually failing test and no something that is not implemented/a TODO. I do not have the time to check for that right now.

Takewaway message: using a newer Chisel version allows to use a way more up-to-date version of Java.


The chisel book is created just fine, as in: LaTeX successfully runs and creates a nice looking pdf file.

I also found the bug in the creation of the slides [here](https://tex.stackexchange.com/questions/713015/unknown-option-pdflatex-for-package-xcolor-edef); a pull request will follow soon.

**Comment by schoeberl** [comment]
Thanks for looking for this. Can you build it with your “normal” latex installation?

I really should have the latex build in the CI.

As there is an error with 6 with FPGA memory initialization, I switched back to 3.6. You can simply switch between Chisel versions by changing comments in the build.sbt. There are entries from 3.5 to 6.

Cheers,
Martin

**Comment by schoeberl** [comment]
The current situation is that Chisel 3.6.1 works with Scala 2.13.14 (which should be good for up to Java 22, but there is a Java 23 out... that needs Scala 2.13.15, but Chisel 6 does not have it.). Chisel 5 does not implement the experimental FPGA memory initialization, Chisel 6 has a bug with it (at least in the way I use it, maybe my code is wrong).

I added the latex build to the CI, which is something long on my TODO list.

Conclusion: 3.6.1 is now on the safe side - will keep it as default for the book. Skip 5 (it also needs manual downloading of the firtool AFAIK). Switch to Chisel 6 is fine (except that use case). The FPGA init issue is submitted.

Thanks again for helping me debug and your fixes.
